FROM php:7.4

WORKDIR /php-container

ENV PORT=8000

EXPOSE $PORT

RUN apt-get update
RUN apt-get install -y libzip-dev libpng-dev libjpeg-dev libfreetype6-dev libpq-dev unzip git curl
RUN docker-php-ext-install pdo pdo_mysql pdo_pgsql

RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
RUN php -r "if (hash_file('sha384', 'composer-setup.php') === 'dac665fdc30fdd8ec78b38b9800061b4150413ff2e3b6f88543c636f7cd84f6db9189d43a81e5503cda447da73c7e5b6') { echo 'Installer verified'.PHP_EOL; } else { echo 'Installer corrupt'.PHP_EOL; unlink('composer-setup.php'); exit(1); }"
RUN php composer-setup.php
RUN php -r "unlink('composer-setup.php');"

RUN mv composer.phar /usr/local/bin/composer

CMD composer install && php artisan key:generate && php artisan serve --host=0.0.0.0 --port=$PORT
