FROM postgres:latest

EXPOSE 5432
# Set environment variables for PostgreSQL
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=libaryPassword
ENV POSTGRES_DB=library_api
# Copy the initialization script into the Docker image


