services:

  container-php:
    container_name: php-projeto-biblioteca
    build:
      context: .
      dockerfile: Dockerfile-php
#    image: imagem-php81:1.0
    pull_policy: never
    ports:
      - "80:80"
    volumes:
      - type: bind
        source: ./server/
        target: /php-container
    networks:
      - compose-bridge


  vue-container:
    container_name: vue-projeto-biblioteca
    build:
      context: .
      dockerfile: Dockerfile-vue
#    image: imagem-vue3:1.0
    pull_policy: never
    volumes:
      - type: bind
        source: ./client/
        target: /vue-container
    ports:
      - "5173:5173"
    depends_on:
      - container-php


  postgres-container:
    container_name: container-para-postgres
    build:
      context: .
      dockerfile: Dockerfile-postgres
#    image: imagem-postgres-latest:1.0
    pull_policy: never
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: libaryPassword
#      POSTGRES_DB: library_api
    env_file:
      - .dockerenv
    ports:
      - "5432:5432"
    volumes:
      - type: bind
        source: dadosPostgres/
        target: /var/lib/postgresql/
    networks:
      - compose-bridge

networks:
  compose-bridge:
    driver: bridge