FROM php:8.1.33-apache

WORKDIR /php-container

ENV PORT=80

EXPOSE $PORT

RUN apt-get update
RUN apt-get install -y libzip-dev libpng-dev libjpeg-dev libfreetype6-dev libpq-dev unzip git curl
RUN docker-php-ext-install pdo pdo_mysql pdo_pgsql

RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
RUN php -r "if (hash_file('sha384', 'composer-setup.php') === 'ed0feb545ba87161262f2d45a633e34f591ebb3381f2e0063c345ebea4d228dd0043083717770234ec00c5a9f9593792') { echo 'Installer verified'.PHP_EOL; } else { echo 'Installer corrupt'.PHP_EOL; unlink('composer-setup.php'); exit(1); }"
RUN php composer-setup.php
RUN php -r "unlink('composer-setup.php');"

RUN mv composer.phar /usr/local/bin/composer

CMD composer install && \
php artisan key:generate && \
php artisan cache:clear && \
php artisan config:clear && \
php artisan route:clear && \
php artisan view:clear && \
php artisan migrate --force && \
php artisan db:seed && \
php artisan serve --host=0.0.0.0 --port=$PORT
