FROM postgres:latest

EXPOSE 5432
# Set environment variables for PostgreSQL
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=postgres
ENV POSTGRES_DB=postgres
# Copy the initialization script into the Docker image


